[package]
name = "zero2prod"
version = "0.1.0"
edition = "2024"

[lib]
path = "src/lib.rs"

[dependencies]
actix-web = "4"
reqwest = "0.12"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }


[dev-dependencies]
reqwest = "0.12"
