application:
  port: 8000
  host: "127.0.0.1"
database:
  host: "app-34069cbd-0bb8-48f7-ae91-3b07ebf78c96-do-user-24355948-0.i.db.ondigitalocean.com"
  port: 25060
  username: "postgres"
  password: "password"
  database_name: "newsletter"
